version: "3.7"

x-defaults: &defaults
  env_file: .env
  deploy:
    resources:
      limits:
        cpus: '0.75'
        memory: 600M
    restart_policy:
      condition: on-failure
      max_attempts: 5
  sysctls:
    net.core.somaxconn: 4096
    net.ipv4.tcp_syncookies: 0
  ulimits:
    nproc: 65536
    nofile:
      soft: 32768
      hard: 65536
  networks:
    - www

services:
  web:
    <<: *defaults
    image: nginx:1.15-alpine
    ports:
      - 8080:80
      - 8433:433
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d/:ro,consistent
      - ./logs/nginx:/var/log/nginx/:rw,consistent
      - ./www:/srv/www/:ro,consistent
    depends_on:
      - phpfpm
          
  phpfpm:
    <<: *defaults
    image: local/php:latest
    build:
      context: .
      dockerfile: dockerfile.build-php
      cache_from:
        - local/php:latest
        - php:7-fpm-alpine
    expose:
      - 9000
    volumes:
      - ./conf/phpfpm/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf:ro,consistent
      - ./conf/phpfpm/zz-docker.ini:/usr/local/etc/php/conf.d/zz-docker.ini:ro,consistent
      - ./logs/phpfpm:/var/log/php-fpm/:rw,consistent
      - ./www:/srv/www/:ro,consistent
    depends_on:
      - mysql

  mysql:
    <<: *defaults
    image: percona/percona-server:5.7
    expose:
      - 3306
    volumes:
      - ./logs/mysql:/var/log/:rw,consistent
      - ./sql:/docker-entrypoint-initdb.d/:ro,consistent
      - mysql-data:/var/lib/mysql/:rw,consistent

volumes:
  mysql-data: {}

networks:
  www:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-www
