version: "3.6"

x-defaults:
  &defaults
  restart: always
  env_file: .env
  networks:
    - www

services:
  web:
    <<: *defaults
    image: nginx:1.15-alpine
    ports:
      - 8080:80
      - 8433:433
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d/:ro,cached
      - ./logs/nginx:/var/log/nginx/:rw,cached
      - ./www:/srv/www/:ro,cached
    depends_on:
      - phpfpm
          
  phpfpm:
    <<: *defaults
    # image: php:7-fpm-alpine
    image: local/php:latest
    build:
      context: .
      dockerfile: dockerfile.php
      cache_from:
        - local/php:latest
        - php:7-fpm-alpine
    expose:
      - 9000
    volumes:
      - ./conf/phpfpm/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf:ro,cached
      - ./conf/phpfpm/zz-docker.ini:/usr/local/etc/php/conf.d/zz-docker.ini:ro,cached
      - ./logs/phpfpm:/var/log/php-fpm/:rw,cached
      - ./www:/srv/www/:ro,cached
    depends_on:
      - mysql

  mysql:
    <<: *defaults
    image: percona/percona-server:5.7
    expose:
      - 3306
    volumes:
      - ./logs/mysql:/var/log/:rw,cached
      - ./sql:/docker-entrypoint-initdb.d/:ro,cached
      - dbdata:/var/lib/mysql/:rw,cached
    
  adminer:
    <<: *defaults
    image: adminer:4.7-standalone
    ports:
      - 8081:8080
    depends_on:
      - mysql

volumes:
  dbdata:

networks:
  www:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-www
