version: "3.7"

x-defaults: &defaults
  env_file:
    - ${ENV_FILE:-environment}
  deploy:
    resources:
      limits:
        cpus: "0.75"
        memory: 512M
    restart_policy:
      condition: any
  sysctls:
    net.core.somaxconn: 16384
    net.ipv4.tcp_syncookies: 0
  ulimits:
    nproc: 65536
    nofile:
      soft: 32768
      hard: 65536
    memlock:
      soft: -1
      hard: -1
  networks:
    - net

services:
  app:
    <<: *defaults
    image: local/php:latest
    build:
      context: .
      dockerfile: dockerfile.build-php
      cache_from:
        - local/php:latest
        - php:7-fpm-alpine
    expose:
      - 9000
    volumes:
      - ./www:/srv/www/:rw,consistent
      - ./logs/phpfpm:/var/log/php-fpm/:rw,consistent
      - ./conf/phpfpm/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf:ro
      - ./conf/phpfpm/zz-docker.ini:/usr/local/etc/php/conf.d/zz-docker.ini:ro
    depends_on:
      - db

  db:
    <<: *defaults
    image: percona/percona-server:${DB_TAG:-5.7}
    expose:
      - 3306
    volumes:
      - mysql-data:/var/lib/mysql/:rw,consistent
      - ./logs/mysql:/var/log/:rw,consistent
      - ./sql:/docker-entrypoint-initdb.d/:ro

  lb:
    <<: *defaults
    image: nginx:${LB_TAG:-1.14-alpine}
    ports:
      - 8080:80
      - 8433:433
    volumes:
      - ./logs/nginx:/var/log/nginx/:rw,consistent
      - ./conf/nginx:/etc/nginx/conf.d/:ro
      - ./www:/srv/www/:ro
    depends_on:
      - app

volumes:
  mysql-data: {}

networks:
  net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-www
