version: "3.6"

x-defaults:
  &defaults
  restart: always
  env_file: .env
  networks:
    - www

services:
  web:
    <<: *defaults
    image: nginx:1.15-alpine
    ports:
      - 8080:80
      - 8433:433
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d/:ro
      - ./logs/nginx:/var/log/nginx/:rw
      - ./www:/srv/www/:ro
    depends_on:
      - phpfpm
          
  phpfpm:
    <<: *defaults
    # image: php:7-fpm-alpine
    image: local/php7
    build:
      context: .
      dockerfile: dockerfile.php7-custom
      cache_from:
        - local/php7
        - php:7-fpm-alpine
    volumes:
      - ./conf/phpfpm/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf:ro
      - ./conf/phpfpm/zz-docker.ini:/usr/local/etc/php/conf.d/zz-docker.ini:ro
      - ./logs/phpfpm:/var/log/php-fpm/:rw
      - ./www:/srv/www/:ro
    depends_on:
      - mysql

  mysql:
    <<: *defaults
    image: percona/percona-server:5.7
    ports:
      - 3306:3306
    volumes:
      - ./logs/mysql:/var/log/mysql/:rw
      - ./sql:/docker-entrypoint-initdb.d/:ro
      - dbdata:/var/lib/mysql/:rw
    environment:
      CHARACTER_SET_SERVER: 'utf8'
      COLLATION_SERVER: 'utf8_general_ci'
    
  adminer:
    <<: *defaults
    image: adminer:4.7-standalone
    ports:
      - 8081:8080
    depends_on:
      - mysql

volumes:
  dbdata:

networks:
  www:
